# Generated by Django 3.2.5 on 2022-06-29 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_board_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
